apiVersion: v1
kind: Service
metadata: 
  {{- if .Values.portal.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.portal.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ template "portal.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "portal.labels" (dict "context" . "component" .Values.portal.name "name" .Values.portal.name) | nindent 4 }}
  {{- if .Values.portal.service.labels }}
  {{- toYaml .Values.portal.service.labels | nindent 4 }}
  {{- end }}  
spec:
  type: {{ .Values.portal.service.type }}
  ports:
    - name: {{ .Values.portal.service.servicePortAccessName }}
      port: {{ .Values.portal.service.servicePortAccess }}
      protocol: TCP
      targetPort: {{ .Values.portal.backend.containerPorts.access }}
    - name: {{ .Values.portal.service.servicePortImportName }}
      port: {{ .Values.portal.service.servicePortImport }}
      protocol: TCP
      targetPort: {{ .Values.portal.backend.containerPorts.import }}
    - name: {{ .Values.portal.service.servicePortHttpName }}
      port: {{ .Values.portal.service.servicePortHttp }}
      protocol: TCP
      targetPort: {{ .Values.portal.frontend.containerPorts.http }}
  selector:
    {{- include "portal.selectorLabels" (dict "context" . "name" .Values.portal.name) | nindent 4 }}